name: ci

on: [push, pull_request]

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"

      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - uses: jiro4989/setup-nim-action@v1

      - uses: cedx/setup-dart@v2

      - uses: goto-bus-stop/setup-zig@v1

      - name: install tools
        run: |
          cargo install cargo-eval
          dotnet tool install -g dotnet-script
          rustup default nightly

      - name: print all versions
        run: |
          rustc --version
          echo
          go version
          echo
          julia --version
          echo
          deno --version
          echo
          python --version
          echo
          gcc --version
          echo
          nim --version
          echo
          dart --version
          echo
          printf 'zig: ' && zig version
          echo
          printf 'dotnet: ' && dotnet --version
          echo
          swift --version

      - name: run all
        run: |
          sed -i 's/python/python3/g' run.sh
          sh run.sh
